### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by kamaradclimber** [knudsvik/EnergyScore#53]
## Version of the custom_component
0.3.1

## Configuration

```yaml
 - platform: energyscore
    name: House Energy Score
    unique_id: a6e5f61a-0761-478a-8520-87612e0c1ea5
    price_entity: sensor.electricity_cost
    energy_entity: sensor.home_energy_meter_gen5_electric_consumed_kw
```

## Describe the bug

Update of the entity fails with:
```
Traceback (most recent call last):
  File "/config/custom_components/energyscore/sensor.py", line 268, in async_update
    self._state = self.process_new_data()
  File "/config/custom_components/energyscore/sensor.py", line 233, in process_new_data
    _norm_prices = normalise_price(self.attr[PRICES])
  File "/config/custom_components/energyscore/sensor.py", line 73, in normalise_price
    return {
  File "/config/custom_components/energyscore/sensor.py", line 74, in <dictcomp>
    key: (max_value - value) / (max_value - min_value)
ZeroDivisionError: float division by zero
```
(line numbers are a bit shifted because I added some log lines to understand the issue).

The price dictionary contains 2 values with the same value (thus the division by zero).

It happens on a setup without nordpool sensor: it's a simple price sensor to follow peak/offpeak price.

**Comment by kamaradclimber** [comment]
I worked around locally by adding:

```
   price_range = max_value - min_value
    if max_value == min_value:
        return { key: 1 for key, value in price_dict.items() }
```
at https://github.com/knudsvik/EnergyScore/blob/master/custom_components/energyscore/sensor.py#L71

**Comment by knudsvik** [comment]
Thanks a lot for reporting bugs 🥇
