### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by knudsvik** [knudsvik/EnergyScore#72]
```python
2023-01-08 10:58:40.994 DEBUG (MainThread) [custom_components.energyscore] UI washer - Calc. energy usage: [0.0, 0.0, 0.0]
2023-01-08 10:58:40.995 DEBUG (MainThread) [custom_components.energyscore] UI washer - Quality: 0.12
2023-01-08 10:58:40.995 ERROR (MainThread) [custom_components.energyscore] UI washer - Could not process the updated data and produce the new EnergyScore
Traceback (most recent call last):
  File "/config/custom_components/energyscore/sensor.py", line 288, in async_update
    self._state = self.process_new_data()
  File "/config/custom_components/energyscore/sensor.py", line 251, in process_new_data
    _norm_energies = normalise_energy(_energy_usage)
  File "/config/custom_components/energyscore/sensor.py", line 94, in normalise_energy
    return {key: value / sum_values for key, value in energy_dict.items()}
  File "/config/custom_components/energyscore/sensor.py", line 94, in <dictcomp>
    return {key: value / sum_values for key, value in energy_dict.items()}
ZeroDivisionError: float division by zero
```

**Comment by knudsvik** [comment]
Possibly reproduce by having data more than 24 hours old in the energy attribute. First update will fail, possibly since all data is wiped? Ok after next update:
```python
2023-01-08 11:18:40.847 DEBUG (MainThread) [custom_components.energyscore] UI washer - Calc. energy usage: []
2023-01-08 11:18:40.848 DEBUG (MainThread) [custom_components.energyscore] UI washer - Quality: 0.0
2023-01-08 11:18:40.848 DEBUG (MainThread) [custom_components.energyscore] UI washer - Not able to calculate energy use in the last 24 hours
```
