### ISSUE TITLE
GUI Installation of integration fails

### ISSUE THREAD

**Issue by jonwaland** [knudsvik/EnergyScore#78]
## Version of the custom_component

v1.0.3
Version: 1.29.1
HASS 2023.1.2
python 3.9.6

## Configuration

Integration works fine from yaml configuraton

## Describe the bug
GUI activation of the integration fails, with the error:
```
Error
Config flow could not be loaded: {"message":"Invalid handler specified"}
```

## Debug log

```
2023-01-13 10:54:15.700 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.energyscore.config_flow
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 744, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 761, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/energyscore/config_flow.py", line 39, in <module>
    class EnergyScoreConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
  File "/home/homeassistant/.homeassistant/custom_components/energyscore/config_flow.py", line 44, in EnergyScoreConfigFlow
    async def async_step_user(self, user_input: dict[str, Any] | None = None):
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'
2023-01-13 10:54:15.702 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration energyscore: Exception importing custom_components.energyscore.config_flow
```

**Comment by knudsvik** [comment]
That’s very strange. I need to look into this, a bit difficult when I am not sure how I can reproduce this, works fine for me in dev and prod..

**Comment by jonwaland** [comment]
any suggestions on what debugs to enable?

```
logger:
  default: warn
  #  logs:
  #  homeassistant.components.zha: debug
  #  bellows.zigbee.application: debug
  #  bellows.ezsp: debug
  #  zigpy: debug
  #  zhaquirks: debug
#    homeassistant.components.dhcp: debug
```

**Comment by knudsvik** [comment]
Debugging would give me more information if I didn't know where the bug originated. I know where this bug appears; the problem is I don't know why or how to recreate it. I am planning to implement some config options for EnergyScore next which probably means I am going to change parts of this code that you experience issues with. Hopefully that will fix it.

**Comment by knudsvik** [comment]
@jonwaland Do you still have issues with this? Have you updated both HA and EnergyScore to latest release?

**Comment by jonwaland** [comment]
Just upgraded HA to 2023.2.2 and EnergyScore was already updated to current release. removed yaml. Restarted. used GUI to add. Worked. 

So seems fixed.
